service: Post-it

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  lambdaHashingVersion: 20201221

  environment:
    tableName: user

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  createUser:
    handler: ./src/routes/user/createUser.main
    events:
      - http:
          path: user
          method: post
          authorizer: aws_iam
  getUser:
    handler: ./src/routes/user/getUser.main
    events:
      - http:
          path: user/{id}
          method: get
          authorizer: aws_iam
  createOrder:
    handler: ./src/routes/order/createOrder.main
    events:
      - http:
          path: order
          method: post
          authorizer: aws_iam
  listOrders:
    handler: ./src/routes/order/listOrders.main
    events:
      - http:
          path: order/{id}
          method: get
          authorizer: aws_iam
  createItem:
    handler: ./src/routes/item/createItem.main
    events:
      - http:
          path: item
          method: post
          authorizer: aws_iam
  listItems:
    handler: ./src/routes/item/listItems.main
    events:
      - http:
          path: item/{order_id}
          method: get
          authorizer: aws_iam
